import requests

BASE_URL = "https://retrocharting.com"
API_URL = "https://retrocharting-backend.onrender.com/api/v1"

def check_url(url, expected_status=200, check_content=None, allow_redirects=True):
    print(f"Checking {url}...")
    try:
        resp = requests.get(url, allow_redirects=allow_redirects, timeout=10)
        status = resp.status_code
        print(f" -> Status: {status}")
        
        if not allow_redirects and status in [301, 308]:
             print(f" -> Redirect Location: {resp.headers.get('Location')}")
             
        if check_content and check_content in resp.text:
            print(f" -> Content Check ('{check_content}'): OK")
        elif check_content:
            print(f" -> Content Check ('{check_content}'): FAILED")
            print(f"    Status: {status}")
            print(f"    Preview: {resp.text[:500]}") # Show first 500 chars to identify if it's Homepage or Error

            
        return resp
    except Exception as e:
        print(f" -> Error: {e}")
        return None

print("--- 1. Checking Robots.txt ---")
check_url(f"{BASE_URL}/robots.txt", check_content="sitemap.xml")

print("\n--- 2. Checking Sitemap Index ---")
# Next.js 15 generated sitemaps usually at /sitemap.xml
resp = check_url(f"{BASE_URL}/sitemap.xml", check_content="sitemap.xml") 
# Logic: If it's an index, it should contain "sitemap.xml" or something similar if generated by Next
# Actually Next 15 generateSitemaps usually creates /sitemap.xml which lists /sitemap/0.xml
# Let's see content.

print("\n--- 3. Checking Redirects (Legacy URL) ---")
# Disable auto-redirect to see the 301
check_url(f"{BASE_URL}/fr/jeux-video/sonic-the-hedgehog", allow_redirects=False)

print("\n--- 4. Checking Backend API Count ---")
check_url(f"{API_URL}/games/count")
